export {
  closeDbClient,
  createDbClient,
  createRetentionWorkerDbClient,
  createServiceWorkerDbClient,
  type Database,
} from "./client.js";
export {
  AppIdentityError,
  findAppUserByAuthId,
  getSystemControl,
  requireActiveAppUser,
  type AppRole,
  type AppUser,
  type SystemControl,
  type SystemControlKey,
} from "./identity.js";
export {
  consumeOAuthState,
  createAmoConnection,
  createOAuthState,
  disableAmoConnection,
  findDueAmoConnectionIds,
  getAmoConnectionCredentials,
  getCurrentSafeAmoConnectionStatus,
  getSafeAmoConnectionStatus,
  purgeExpiredOAuthStates,
  withLockedAmoConnection,
  type AmoConnectionCredentials,
  type AmoConnectionStatusValue,
  type CreatedOAuthState,
  type CreateAmoConnectionInput,
  type LockedAmoConnectionActions,
  type OAuthState,
  type SafeAmoConnectionStatus,
} from "./amo-connections.js";
export {
  activatePipelineConfig,
  getActivePipelineConfig,
  type ActivatePipelineConfigInput,
  type ActiveChannelRule,
  type ActivePipelineConfig,
} from "./amo-config.js";
export {
  finishSyncRun,
  startSyncRun,
  type StartSyncRunInput,
  type SyncCounts,
  type SyncCursorPosition,
  type SyncKind,
  type SyncOutcome,
  type SyncRun,
  type SyncStatus,
  type SyncStream,
} from "./sync-runs.js";
export {
  appendAmoApiAudit,
  appendRawPage,
  getRawChannelValues,
  quarantineRawPage,
  type AmoApiAuditInput,
  type AppendRawPageInput,
  type QuarantineRawPageInput,
  type RawAmoEventInput,
  type RawAmoObjectInput,
  type RawChannelValue,
  type RawEntityType,
} from "./raw-amo.js";
export {
  deleteProvenRawBefore,
  claimNextSyncWork,
  completeSyncWork,
  enqueueSyncWork,
  failStaleSyncRuns,
  getLatestSyncRun,
  getPreviousFullLeadCount,
  getSyncCursors,
  getSyncRunDetail,
  isSyncAdvisoryLockBusy,
  listSyncRuns,
  recordRawRetentionProofs,
  sweepExpiredSyncWork,
  withSyncAdvisoryLock,
  type ClaimedSyncWork,
  type CompleteSyncWorkInput,
  type RawRetentionProofInput,
  type RawRetentionResult,
  type RawRetentionSourceTable,
  type QueuedSyncWork,
  type SafeSyncRunDetail,
  type SafeSyncRunSummary,
  type SyncLockFence,
} from "./sync-operations.js";
export {
  createNormalizedLeadRepository,
  type AppendResponsibleEventInput,
  type AppendStageEventInput,
  type NormalizedLeadKey,
  type NormalizedLeadRepository,
  type UpsertAmoUserInput,
  type UpsertLeadInput,
  type UpsertLeadMilestoneInput,
  type UpsertPipelineStatusInput,
} from "./leads.js";
export {
  createNormalizeRunRepository,
  type NormalizationRun,
  type NormalizationWritePlan,
  type NormalizationWriteResult,
  type NormalizeRunRepository,
  type NormalizedLeadWrite,
  type RawEntitySnapshot,
  type RawHistoryEventRow,
  type RawLeadSnapshot,
} from "./normalize-run.js";
export {
  PROTECTED_SPREADSHEET_ID,
  activateSheetTarget,
  createSheetTarget,
  disableSheetTarget,
  finishSheetPublication,
  getSheetTarget,
  listSheetTargets,
  getActiveSheetTarget,
  getSuccessfulPublication,
  listSheetLayoutMappings,
  listSheetPublications,
  markSheetTargetValidated,
  replaceSheetLayoutMappings,
  startSheetPublication,
  type CreateSheetTargetInput,
  type FinishPublicationInput,
  type PublicationStatus,
  type ReplaceLayoutMappingInput,
  type SheetLayoutMapping,
  type SheetPublication,
  type SheetReportKind,
  type SheetTarget,
  type SheetTargetStatus,
  type SheetValueType,
  type StartPublicationInput,
} from "./sheets.js";
export {
  acknowledgeAlert,
  countOpenAlerts,
  listAlerts,
  raiseAlert,
  resolveAlert,
  type AlertSeverity,
  type AlertStatus,
  type RaiseAlertInput,
  type SystemAlert,
} from "./alerts.js";
export {
  withCurrentSnapshot,
  type SnapshotMeta,
} from "./dashboard/with-snapshot.js";
export {
  type DashboardQueryFilters,
  type DashboardQueryScope,
} from "./dashboard/cells.js";
export {
  getOverview,
  type DashboardOverviewData,
  type OverviewInput,
} from "./dashboard/overview.js";
export {
  getManagerMetrics,
  type ManagerMetricRow,
  type ManagerMetrics,
} from "./dashboard/managers.js";
export {
  getChannelMetrics,
  type ChannelMetricRow as DashboardChannelRow,
  type ChannelMetrics,
} from "./dashboard/channels.js";
export {
  getDrilldown,
  type DrilldownInput,
  type DrilldownPosition,
  type DrilldownResult,
} from "./dashboard/drilldown.js";
export {
  getLeadDetail,
  type LeadDetail,
  type LeadDetailViewer,
  type LeadStageHistoryEntry,
} from "./dashboard/lead-detail.js";
export {
  getAttention,
  type AttentionResult,
} from "./dashboard/attention.js";
export {
  getFunnelMetrics,
  type FunnelMetrics,
  type FunnelStage,
} from "./dashboard/funnel.js";
export {
  approveSnapshot,
  createMetricSnapshot,
  exportComparableRows,
  getCurrentSnapshot,
  getSnapshotByVersion,
  listSnapshotCells,
  rejectSnapshot,
  validateSnapshot,
  type CreateSnapshotInput,
  type MetricCellInput,
  type MetricLeadFactInput,
  type MetricSnapshot,
  type ComparableMetricRow,
  type ComparableSnapshotRows,
  type SnapshotCell,
  type SnapshotStatus,
  type SnapshotValidation,
  type StageSnapshotRowInput,
} from "./snapshots.js";
export {
  getCurrentSalesPlan,
  listSalesPlans,
  setSalesPlanTarget,
  type PlanMetricKey,
  type SalesPlan,
  type SetSalesPlanInput,
} from "./sales-plans.js";
export {
  acceptQualityIssue,
  createQualityRepository,
  listQualityIssues,
  summarizeOpenQualityIssues,
  type AcceptQualityIssueInput,
  type OpenQualityIssueInput,
  type QualityIssue,
  type QualityIssueFilter,
  type QualityIssuePage,
  type QualityRepository,
  type QualitySeverity,
  type QualityStatus,
  type ResolveAbsentIssuesInput,
} from "./quality.js";
