export {
  parseServerEnv,
  ServerEnvValidationError,
  type ServerEnv,
} from "./env.js";
export { failure, success, type ApiFailure, type ApiMeta, type ApiSuccess } from "./api-envelope.js";
export { AppError, type AppErrorCode } from "./errors.js";
export {
  INITIAL_CHANNEL_RULES,
  amoConfigDiscoverySchema,
  channelMatchTypeSchema,
  channelRuleCandidateSchema,
  checksumAmoConfigDiscovery,
  normalizedChannelSchema,
  pipelineConfigCandidateSchema,
  validateChannelRules,
  validatePipelineConfig,
  type AmoConfigDiscovery,
  type ChannelRuleCandidate,
  type PipelineConfigCandidate,
  type PipelineConfigValidation,
  type ResolvedPipelineConfig,
} from "./amo/config.js";
export {
  BUSINESS_TIME_ZONE,
  MAX_UNIX_SECONDS,
  parseIsoInstant,
  toMoscowDate,
  unixSecondsToInstant,
} from "./time/moscow-date.js";
export {
  MAX_AMO_PRICE_RUBLES,
  isRubles,
  isZeroRubles,
  parseAmoRubles,
  parseRubleDecimal,
  type AmoRublesResult,
  type InvalidRublesReason,
  type Rubles,
} from "./money/rubles.js";
export {
  NON_TEXT_SOURCE_VALUE,
  extractChannelInput,
  matchChannel,
  type ChannelInput,
  type ChannelMatch,
  type ChannelMatchReason,
  type ChannelMatchType,
  type ChannelRule,
  type NormalizedChannel,
} from "./leads/channel.js";
export {
  DASHBOARD_DRILLDOWN_METRICS,
  attentionSchema,
  channelsTableSchema,
  dailyPointSchema,
  dashboardFiltersEchoSchema,
  dashboardMetaSchema,
  dashboardOverviewSchema,
  drilldownMetricSchema,
  drilldownPageSchema,
  drilldownRowSchema,
  funnelSchema,
  managersTableSchema,
  metricDeltaSchema,
  metricTotalsSchema,
  planProgressSchema,
  qualitySummarySchema,
  type AttentionReport,
  type ChannelsTable,
  type DailyPoint,
  type DashboardMeta,
  type DashboardOverview,
  type DrilldownMetric,
  type DrilldownPage,
  type DrilldownRow,
  type FunnelReport,
  type ManagersTable,
  type MetricDelta,
  type MetricTotals,
  type PlanProgress,
} from "./dashboard/contracts.js";
export {
  decodeDrilldownCursor,
  deriveCursorKey,
  encodeDrilldownCursor,
  filterHashOf,
  maskPhone,
  type DrilldownCursor,
} from "./dashboard/cursor.js";
export {
  parseDashboardFilters,
  type DashboardFilters,
  type ParseDashboardFiltersOptions,
} from "./dashboard/filters.js";
export {
  deriveDashboardScope,
  managerKeysOf,
  type DashboardRole,
  type DashboardScope,
  type DashboardSession,
} from "./dashboard/scope.js";
export {
  aggregateByChannel,
  aggregateByManager,
  aggregateDaily,
  aggregateMetrics,
  conversion,
  deltaPct,
  moneyAverage,
  planCompletion,
} from "./metrics/aggregate.js";
export {
  dateRangeLength,
  eachDate,
  formatDate,
  isDateInRange,
  previousPeriod,
} from "./metrics/periods.js";
export type {
  AggregateInput,
  ChannelMetricRow,
  DailyMetricRow,
  ManagerMetricRow,
  MetricAggregate,
  MetricDateRange,
  MetricFilters,
  MetricLeadFact,
} from "./metrics/types.js";
export {
  QUALITY_CODES,
  QUALITY_CODE_POLICY,
  isAcceptableQualityCode,
  isQualityCode,
  qualityCodeBlocks,
  qualityCounterKey,
  type QualityCode,
  type QualityCodePolicy,
  type QualityCounterKey,
} from "./quality/codes.js";
export {
  emptyQualitySummary,
  evaluateQualityGate,
  type QualityGateOptions,
  type QualityGateResult,
  type QualitySummary,
} from "./quality/gates.js";
export {
  HISTORY_ISSUE_SEVERITY,
  buildLeadHistory,
  extractHistoryEvent,
  type BuildLeadHistoryInput,
  type HistoryEventExtraction,
  type LeadHistoryEvent,
  type LeadHistoryIssueCandidate,
  type LeadHistoryIssueCode,
  type LeadHistoryResult,
  type LeadMilestones,
  type LeadResponsibility,
  type LeadResponsibleEventRecord,
  type LeadStageEventRecord,
  type LeadStageStay,
  type PipelineStatusOrder,
  type RawHistoryEvent,
} from "./leads/build-history.js";
export {
  LEAD_ISSUE_SEVERITY,
  displayNameFor,
  normalizeLead,
  type LeadQualityCode,
  type LeadQualityIssueCandidate,
  type LeadQualitySeverity,
  type NormalizedLead,
  type NormalizedLeadResult,
  type NormalizeLeadConfig,
  type NormalizeLeadContext,
} from "./leads/normalize-lead.js";
